services:
  nginx:
    image: nginx:alpine
    container_name: lab7_nginx
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  rabbitmq:
    image: rabbitmq:3-management
    container_name: lab7_rabbit
    ports:
      - "5672:5672"
      - "15672:15672"

  php:
    build: .
    container_name: lab7_php
    volumes:
      - ./www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    expose:
      - "9000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: lab7_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: lab5_db
      MYSQL_USER: lab5_user
      MYSQL_PASSWORD: lab5_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: lab7_adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  db_data: